# Week 4 assessment - segmenting and clustering neighbourhoods in Toronto

### Section 1 - preparing the first dataframe

In [1]:
#importing required libraries

import pandas as pd
import numpy as np
import matplotlib.cm as cm
import matplotlib.colors as colors
import json
import requests
from pandas.io.json import json_normalize
from sklearn.cluster import KMeans

In [2]:
# Webpage url                                                                                                               
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

# Extract tables
dfs = pd.read_html(url)

# Get first table                                                                                                           
df = dfs[0]

# Extract columns                                                                                                           
df2 = df[['Postal Code','Borough', 'Neighbourhood']]
print(df2)

    Postal Code           Borough  \
0           M1A      Not assigned   
1           M2A      Not assigned   
2           M3A        North York   
3           M4A        North York   
4           M5A  Downtown Toronto   
..          ...               ...   
175         M5Z      Not assigned   
176         M6Z      Not assigned   
177         M7Z      Not assigned   
178         M8Z         Etobicoke   
179         M9Z      Not assigned   

                                         Neighbourhood  
0                                         Not assigned  
1                                         Not assigned  
2                                            Parkwoods  
3                                     Victoria Village  
4                            Regent Park, Harbourfront  
..                                                 ...  
175                                       Not assigned  
176                                       Not assigned  
177                                       

In [3]:
df = pd.DataFrame(df2)

In [4]:
#Replace Not assigned with Nan
df.replace("Not assigned", np.nan, inplace = True)

In [5]:
#  drop  row with NaN in column
df.dropna(subset=["Borough"], axis=0, inplace=True)

In [6]:
#grouping data
df.groupby(by=["Postal Code"])

In [7]:
# reset index, because we droped  rows 
df.reset_index(drop=True, inplace=True)
df

Postal Code           Borough  \
0           M3A        North York   
1           M4A        North York   
2           M5A  Downtown Toronto   
3           M6A        North York   
4           M7A  Downtown Toronto   
..          ...               ...   
98          M8X         Etobicoke   
99          M4Y  Downtown Toronto   
100         M7Y      East Toronto   
101         M8Y         Etobicoke   
102         M8Z         Etobicoke   

                                         Neighbourhood  
0                                            Parkwoods  
1                                     Victoria Village  
2                            Regent Park, Harbourfront  
3                     Lawrence Manor, Lawrence Heights  
4          Queen's Park, Ontario Provincial Government  
..                                                 ...  
98       The Kingsway, Montgomery Road, Old Mill North  
99                                Church and Wellesley  
100  Business reply mail Processing Centre, South C...  
101  Old Mill South, King's Mill Park, Sunnylea, Hu...  
102  Mimico NW, The Queensway West, South of Bloor,...  

[103 rows x 3 columns]

In [8]:
#get shape
df.shape

(103, 3)

### Section 2 - adding location data to the dataframe

In [9]:
#Getting geolocation data - geocoder wouldn't work
df2 = pd.read_csv('Jupyter projects/Geospatial_Coordinates.csv')

In [10]:
#merging the dataframes
g_df = pd.merge(df, df2, on ="Postal Code")
g_df

Postal Code           Borough  \
0           M3A        North York   
1           M4A        North York   
2           M5A  Downtown Toronto   
3           M6A        North York   
4           M7A  Downtown Toronto   
..          ...               ...   
98          M8X         Etobicoke   
99          M4Y  Downtown Toronto   
100         M7Y      East Toronto   
101         M8Y         Etobicoke   
102         M8Z         Etobicoke   

                                         Neighbourhood   Latitude  Longitude  
0                                            Parkwoods  43.753259 -79.329656  
1                                     Victoria Village  43.725882 -79.315572  
2                            Regent Park, Harbourfront  43.654260 -79.360636  
3                     Lawrence Manor, Lawrence Heights  43.718518 -79.464763  
4          Queen's Park, Ontario Provincial Government  43.662301 -79.389494  
..                                                 ...        ...        ...  
98       The Kingsway, Montgomery Road, Old Mill North  43.653654 -79.506944  
99                                Church and Wellesley  43.665860 -79.383160  
100  Business reply mail Processing Centre, South C...  43.662744 -79.321558  
101  Old Mill South, King's Mill Park, Sunnylea, Hu...  43.636258 -79.498509  
102  Mimico NW, The Queensway West, South of Bloor,...  43.628841 -79.520999  

[103 rows x 5 columns]

### Section 3 - clustering neighbourhoods in Toronto

In [11]:
pip install geopy

Note: you may need to restart the kernel to use updated packages.


In [12]:
#locating Toronto

import geopy

from geopy.geocoders import Nominatim

address = 'Toronto, Ontario'

geolocator = Nominatim(user_agent="toronto_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude


print(latitude, longitude)

43.6534817 -79.3839347


In [13]:
pip install folium

Note: you may need to restart the kernel to use updated packages.


In [14]:
#mapping Toronto

import folium
map_Toronto = folium.Map(location=[latitude, longitude], zoom_start=11)

for latitude, longitude, borough, neighbourhood in zip(g_df['Latitude'], g_df['Longitude'], g_df['Borough'], g_df['Neighbourhood']):
    label = '{}, {}'.format(neighbourhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [latitude, longitude],
        radius=3,
        popup=label,
        color='black',
        fill=False
        ).add_to(map_Toronto)  
    
map_Toronto

In [15]:
#Foursquare credentials

CLIENT_ID = '0OUHXELE02ZFO23HNGXFPEGIQB455W2Y4LZR2OC0WDEY5LBK' 
CLIENT_SECRET = 'ZDRJM1OYQGOQ0GY4JCMVBE0S1NQMJRFQD2NSH2CXBFHBIEEC' 
VERSION = '20180604'
LIMIT = 100
radius = 500

In [16]:
#Defining the global url and reviewing request
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, VERSION, latitude, longitude, radius, LIMIT)
    
requests.get(url).json()

{'meta': {'code': 200, 'requestId': '5fbbf0e3556f3329950d3063'},
 'response': {'suggestedFilters': {'header': 'Tap to show:',
   'filters': [{'name': 'Open now', 'key': 'openNow'}]},
  'headerLocation': 'Islington - City Centre West',
  'headerFullLocation': 'Islington - City Centre West, Toronto',
  'headerLocationGranularity': 'neighborhood',
  'totalResults': 16,
  'suggestedBounds': {'ne': {'lat': 43.6333408045, 'lng': -79.51479402615583},
   'sw': {'lat': 43.6243407955, 'lng': -79.52720477384419}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4bc9f9b6b6c49c7469688f91',
       'name': 'South St. Burger',
       'location': {'address': '1020 Islington Ave',
        'lat': 43.63131374571208,
        'lng': -79.51840794740386,
        'labeledLatLngs': [{'label': 'di

In [17]:
#Creating a function to explore nearby venues
def getNearbyVenues(names, latitudes, longitudes):
    radius=500
    LIMIT=100
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, VERSION, lat, lng, radius, LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighbourhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)


In [18]:
#running the function
toronto_venues = getNearbyVenues(names = g_df['Neighbourhood'],
                                   latitudes = g_df['Latitude'],
                                   longitudes = g_df['Longitude']
                                  )

Parkwoods
Victoria Village
Regent Park, Harbourfront
Lawrence Manor, Lawrence Heights
Queen's Park, Ontario Provincial Government
Islington Avenue, Humber Valley Village
Malvern, Rouge
Don Mills
Parkview Hill, Woodbine Gardens
Garden District, Ryerson
Glencairn
West Deane Park, Princess Gardens, Martin Grove, Islington, Cloverdale
Rouge Hill, Port Union, Highland Creek
Don Mills
Woodbine Heights
St. James Town
Humewood-Cedarvale
Eringate, Bloordale Gardens, Old Burnhamthorpe, Markland Wood
Guildwood, Morningside, West Hill
The Beaches
Berczy Park
Caledonia-Fairbanks
Woburn
Leaside
Central Bay Street
Christie
Cedarbrae
Hillcrest Village
Bathurst Manor, Wilson Heights, Downsview North
Thorncliffe Park
Richmond, Adelaide, King
Dufferin, Dovercourt Village
Scarborough Village
Fairview, Henry Farm, Oriole
Northwood Park, York University
East Toronto, Broadview North (Old East York)
Harbourfront East, Union Station, Toronto Islands
Little Portugal, Trinity
Kennedy Park, Ionview, East Birchmo

Now that we have venue information for each neighbourhood, we need to analyse which of these are most popular for each neighbourhood. As these are categorical variables, we need to replace these with numeric, so we use one hot encoding

In [19]:
# one hot encoding
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
toronto_onehot['Neighbourhood'] = toronto_venues['Neighbourhood'] 

# move neighborhood column to the first column
fixed_columns = [toronto_onehot.columns[-1]] + list(toronto_onehot.columns[:-1])
toronto_onehot = toronto_onehot[fixed_columns]

toronto_onehot

Neighbourhood  Accessories Store  \
0                                             Parkwoods                  0   
1                                             Parkwoods                  0   
2                                      Victoria Village                  0   
3                                      Victoria Village                  0   
4                                      Victoria Village                  0   
...                                                 ...                ...   
2162  Mimico NW, The Queensway West, South of Bloor,...                  0   
2163  Mimico NW, The Queensway West, South of Bloor,...                  0   
2164  Mimico NW, The Queensway West, South of Bloor,...                  0   
2165  Mimico NW, The Queensway West, South of Bloor,...                  0   
2166  Mimico NW, The Queensway West, South of Bloor,...                  0   

      Afghan Restaurant  Airport  Airport Food Court  Airport Gate  \
0                     0        0                   0             0   
1                     0        0                   0             0   
2                     0        0                   0             0   
3                     0        0                   0             0   
4                     0        0                   0             0   
...                 ...      ...                 ...           ...   
2162                  0        0                   0             0   
2163                  0        0                   0             0   
2164                  0        0                   0             0   
2165                  0        0                   0             0   
2166                  0        0                   0             0   

      Airport Lounge  Airport Service  Airport Terminal  American Restaurant  \
0                  0                0                 0                    0   
1                  0                0                 0                    0   
2                  0                0                 0                    0   
3                  0                0                 0                    0   
4                  0                0                 0                    0   
...              ...              ...               ...                  ...   
2162               0                0                 0                    0   
2163               0                0                 0                    0   
2164               0                0                 0                    0   
2165               0                0                 0                    0   
2166               0                0                 0                    0   

      ...  Train Station  Turkish Restaurant  Vegetarian / Vegan Restaurant  \
0     ...              0                   0                              0   
1     ...              0                   0                              0   
2     ...              0                   0                              0   
3     ...              0                   0                              0   
4     ...              0                   0                              0   
...   ...            ...                 ...                            ...   
2162  ...              0                   0                              0   
2163  ...              0                   0                              0   
2164  ...              0                   0                              0   
2165  ...              0                   0                              0   
2166  ...              0                   0                              0   

      Video Game Store  Vietnamese Restaurant  Warehouse Store  Wine Bar  \
0                    0                      0                0         0   
1                    0                      0                0         0   
2                    0                      0                0         0   
3                    0                      0     

We then calculate the means of each instance of venue, to get the most popular across the neighbourhoods

In [20]:
# Group rows by neighbourhood and calculate means
toronto_grouped = toronto_onehot.groupby('Neighbourhood').mean().reset_index()
toronto_grouped

Neighbourhood  Accessories Store  \
0                                         Agincourt                0.0   
1                            Alderwood, Long Branch                0.0   
2   Bathurst Manor, Wilson Heights, Downsview North                0.0   
3                                   Bayview Village                0.0   
4                 Bedford Park, Lawrence Manor East                0.0   
..                                              ...                ...   
91                      Willowdale, Willowdale West                0.0   
92                                           Woburn                0.0   
93                                 Woodbine Heights                0.0   
94                                  York Mills West                0.0   
95                         York Mills, Silver Hills                0.0   

    Afghan Restaurant  Airport  Airport Food Court  Airport Gate  \
0                 0.0      0.0                 0.0           0.0   
1                 0.0      0.0                 0.0           0.0   
2                 0.0      0.0                 0.0           0.0   
3                 0.0      0.0                 0.0           0.0   
4                 0.0      0.0                 0.0           0.0   
..                ...      ...                 ...           ...   
91                0.0      0.0                 0.0           0.0   
92                0.0      0.0                 0.0           0.0   
93                0.0      0.0                 0.0           0.0   
94                0.0      0.0                 0.0           0.0   
95                0.0      0.0                 0.0           0.0   

    Airport Lounge  Airport Service  Airport Terminal  American Restaurant  \
0              0.0              0.0               0.0             0.000000   
1              0.0              0.0               0.0             0.000000   
2              0.0              0.0               0.0             0.000000   
3              0.0              0.0               0.0             0.000000   
4              0.0              0.0               0.0             0.045455   
..             ...              ...               ...                  ...   
91             0.0              0.0               0.0             0.000000   
92             0.0              0.0               0.0             0.000000   
93             0.0              0.0               0.0             0.000000   
94             0.0              0.0               0.0             0.000000   
95             0.0              0.0               0.0             0.000000   

    ...  Train Station  Turkish Restaurant  Vegetarian / Vegan Restaurant  \
0   ...            0.0                 0.0                            0.0   
1   ...            0.0                 0.0                            0.0   
2   ...            0.0                 0.0                            0.0   
3   ...            0.0                 0.0                            0.0   
4   ...            0.0                 0.0                            0.0   
..  ...            ...                 ...                            ...   
91  ...            0.0                 0.0                            0.0   
92  ...            0.0                 0.0                            0.0   
93  ...            0.0                 0.0                            0.0   
94  ...            0.0                 0.0                            0.0   
95  ...            0.0                 0.0                            0.0   

    Video Game Store  Vietnamese Restaurant  Warehouse Store  Wine Bar  \
0                0.0                    0.0              0.0       0.0   
1                0.0                    0.0              0.0       0.0   
2                0.0                    0.0              0.0       0.0   
3                0.0                    0.0              0.0       0.0   
4                0.0                    0.0              0.0       0.0   
..               ...      

In [21]:
#pandas dataframe
num_top_venues = 5
for neigh in toronto_grouped['Neighbourhood']:
    print("----"+neigh+"----")
    temp = toronto_grouped[toronto_grouped['Neighbourhood'] == neigh].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Agincourt----
                       venue  freq
0             Clothing Store   0.2
1             Breakfast Spot   0.2
2                     Lounge   0.2
3               Skating Rink   0.2
4  Latin American Restaurant   0.2


----Alderwood, Long Branch----
            venue  freq
0     Pizza Place  0.29
1             Gym  0.14
2  Sandwich Place  0.14
3             Pub  0.14
4     Coffee Shop  0.14


----Bathurst Manor, Wilson Heights, Downsview North----
                       venue  freq
0                Coffee Shop  0.10
1                       Bank  0.10
2                   Pharmacy  0.05
3  Middle Eastern Restaurant  0.05
4              Shopping Mall  0.05


----Bayview Village----
                 venue  freq
0  Japanese Restaurant  0.25
1   Chinese Restaurant  0.25
2                 Bank  0.25
3                 Café  0.25
4    Accessories Store  0.00


----Bedford Park, Lawrence Manor East----
                venue  freq
0      Sandwich Place  0.09
1         Coffee Shop  0.09

In [22]:
#write a function to sort the venues in descending order.
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [23]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighbourhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighbourhood'] = toronto_grouped['Neighbourhood']

for ind in np.arange(toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.shape

(96, 11)

Next, we use KMeans Clustering, to group together similair neighbourhoods, based on their common nearby variables

**Iteration 1**

In [24]:
# set number of clusters by K Means
kclusters = 13

toronto_grouped_clustering = toronto_grouped.drop('Neighbourhood', 1)
# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=1).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
print(kmeans.labels_[0:10])
print(len(kmeans.labels_))

[1 1 1 1 1 1 1 1 1 1]
96


In [25]:
kmeans.labels_

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,
        0,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, 12,  4,  1,  1,  1,  1,  1,  1,  2,  1,  1, 11,  2,
        1,  6,  1,  2,  1,  1,  1,  3,  1,  1,  8,  1,  1,  1,  2,  1,  3,
        1,  1,  6,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  5,  1,  1,  1,
        1,  9,  1, 10,  1,  1,  1,  1,  1,  2,  7], dtype=int32)

In [26]:
toronto_merged = g_df
toronto_merged

Postal Code           Borough  \
0           M3A        North York   
1           M4A        North York   
2           M5A  Downtown Toronto   
3           M6A        North York   
4           M7A  Downtown Toronto   
..          ...               ...   
98          M8X         Etobicoke   
99          M4Y  Downtown Toronto   
100         M7Y      East Toronto   
101         M8Y         Etobicoke   
102         M8Z         Etobicoke   

                                         Neighbourhood   Latitude  Longitude  
0                                            Parkwoods  43.753259 -79.329656  
1                                     Victoria Village  43.725882 -79.315572  
2                            Regent Park, Harbourfront  43.654260 -79.360636  
3                     Lawrence Manor, Lawrence Heights  43.718518 -79.464763  
4          Queen's Park, Ontario Provincial Government  43.662301 -79.389494  
..                                                 ...        ...        ...  
98       The Kingsway, Montgomery Road, Old Mill North  43.653654 -79.506944  
99                                Church and Wellesley  43.665860 -79.383160  
100  Business reply mail Processing Centre, South C...  43.662744 -79.321558  
101  Old Mill South, King's Mill Park, Sunnylea, Hu...  43.636258 -79.498509  
102  Mimico NW, The Queensway West, South of Bloor,...  43.628841 -79.520999  

[103 rows x 5 columns]

In [27]:
toronto_merged = g_df

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged_it1 = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighbourhood'), on='Neighbourhood')

toronto_merged_it1.head() # check the last columns!

Postal Code           Borough                                Neighbourhood  \
0         M3A        North York                                    Parkwoods   
1         M4A        North York                             Victoria Village   
2         M5A  Downtown Toronto                    Regent Park, Harbourfront   
3         M6A        North York             Lawrence Manor, Lawrence Heights   
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government   

    Latitude  Longitude 1st Most Common Venue 2nd Most Common Venue  \
0  43.753259 -79.329656                  Park     Food & Drink Shop   
1  43.725882 -79.315572           Pizza Place          Hockey Arena   
2  43.654260 -79.360636           Coffee Shop                  Park   
3  43.718518 -79.464763        Clothing Store     Accessories Store   
4  43.662301 -79.389494           Coffee Shop           Yoga Studio   

  3rd Most Common Venue 4th Most Common Venue   5th Most Common Venue  \
0           Yoga Studio   Dumpling Restaurant     Distribution Center   
1     French Restaurant           Coffee Shop   Portuguese Restaurant   
2                Bakery                   Pub          Breakfast Spot   
3              Boutique             Gift Shop  Furniture / Home Store   
4                  Bank              Beer Bar           Smoothie Shop   

  6th Most Common Venue       7th Most Common Venue 8th Most Common Venue  \
0              Dive Bar                     Dog Run      Doner Restaurant   
1          Intersection  Construction & Landscaping                 Diner   
2                  Café                     Theater                   Spa   
3           Event Space                 Coffee Shop         Women's Store   
4        Sandwich Place                        Café            Restaurant   

   9th Most Common Venue 10th Most Common Venue  
0             Donut Shop              Drugstore  
1   Ethiopian Restaurant            Escape Room  
2                Brewery             Shoe Store  
3  Vietnamese Restaurant        Airport Service  
4     Chinese Restaurant  Portuguese Restaurant

In [28]:
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighbourhood'],kmeans.labels_):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

**Iteration 2**

In [29]:
# set number of clusters by K Means
kclusters = 10

toronto_grouped_clustering = toronto_grouped.drop('Neighbourhood', 1)
# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=1).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
print(kmeans.labels_[0:10])
print(len(kmeans.labels_))

[1 5 5 5 5 5 5 5 1 5]
96


In [30]:
kmeans.labels_

array([1, 5, 5, 5, 5, 5, 5, 5, 1, 5, 0, 5, 1, 5, 5, 5, 5, 5, 5, 5, 1, 5,
       5, 1, 1, 1, 0, 5, 5, 5, 1, 5, 1, 1, 1, 5, 5, 5, 5, 4, 1, 5, 5, 5,
       1, 5, 1, 5, 5, 8, 1, 5, 1, 5, 1, 5, 6, 5, 4, 5, 5, 0, 5, 5, 5, 0,
       1, 7, 5, 1, 1, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 9, 5, 5, 5, 5, 3, 5,
       0, 1, 5, 5, 5, 1, 0, 2], dtype=int32)

In [31]:
toronto_merged = g_df
toronto_merged

Postal Code           Borough  \
0           M3A        North York   
1           M4A        North York   
2           M5A  Downtown Toronto   
3           M6A        North York   
4           M7A  Downtown Toronto   
..          ...               ...   
98          M8X         Etobicoke   
99          M4Y  Downtown Toronto   
100         M7Y      East Toronto   
101         M8Y         Etobicoke   
102         M8Z         Etobicoke   

                                         Neighbourhood   Latitude  Longitude  
0                                            Parkwoods  43.753259 -79.329656  
1                                     Victoria Village  43.725882 -79.315572  
2                            Regent Park, Harbourfront  43.654260 -79.360636  
3                     Lawrence Manor, Lawrence Heights  43.718518 -79.464763  
4          Queen's Park, Ontario Provincial Government  43.662301 -79.389494  
..                                                 ...        ...        ...  
98       The Kingsway, Montgomery Road, Old Mill North  43.653654 -79.506944  
99                                Church and Wellesley  43.665860 -79.383160  
100  Business reply mail Processing Centre, South C...  43.662744 -79.321558  
101  Old Mill South, King's Mill Park, Sunnylea, Hu...  43.636258 -79.498509  
102  Mimico NW, The Queensway West, South of Bloor,...  43.628841 -79.520999  

[103 rows x 5 columns]

In [32]:
toronto_merged = g_df

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged_it2 = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighbourhood'), on='Neighbourhood')

toronto_merged_it2.head()

Postal Code           Borough                                Neighbourhood  \
0         M3A        North York                                    Parkwoods   
1         M4A        North York                             Victoria Village   
2         M5A  Downtown Toronto                    Regent Park, Harbourfront   
3         M6A        North York             Lawrence Manor, Lawrence Heights   
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government   

    Latitude  Longitude 1st Most Common Venue 2nd Most Common Venue  \
0  43.753259 -79.329656                  Park     Food & Drink Shop   
1  43.725882 -79.315572           Pizza Place          Hockey Arena   
2  43.654260 -79.360636           Coffee Shop                  Park   
3  43.718518 -79.464763        Clothing Store     Accessories Store   
4  43.662301 -79.389494           Coffee Shop           Yoga Studio   

  3rd Most Common Venue 4th Most Common Venue   5th Most Common Venue  \
0           Yoga Studio   Dumpling Restaurant     Distribution Center   
1     French Restaurant           Coffee Shop   Portuguese Restaurant   
2                Bakery                   Pub          Breakfast Spot   
3              Boutique             Gift Shop  Furniture / Home Store   
4                  Bank              Beer Bar           Smoothie Shop   

  6th Most Common Venue       7th Most Common Venue 8th Most Common Venue  \
0              Dive Bar                     Dog Run      Doner Restaurant   
1          Intersection  Construction & Landscaping                 Diner   
2                  Café                     Theater                   Spa   
3           Event Space                 Coffee Shop         Women's Store   
4        Sandwich Place                        Café            Restaurant   

   9th Most Common Venue 10th Most Common Venue  
0             Donut Shop              Drugstore  
1   Ethiopian Restaurant            Escape Room  
2                Brewery             Shoe Store  
3  Vietnamese Restaurant        Airport Service  
4     Chinese Restaurant  Portuguese Restaurant

In [33]:
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighbourhood'],kmeans.labels_):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

**Iteration 3**

In [34]:
# set number of clusters by K Means
kclusters = 7

toronto_grouped_clustering = toronto_grouped.drop('Neighbourhood', 1)
# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=1).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
print(kmeans.labels_[0:10])
print(len(kmeans.labels_))

[1 3 1 1 1 1 1 1 1 1]
96


In [35]:
kmeans.labels_

array([1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3, 5, 1, 1, 1, 1,
       3, 1, 0, 1, 1, 1, 6, 1, 1, 1, 6, 1, 1, 1, 5, 1, 3, 0, 1, 1, 1, 0,
       1, 6, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4, 3,
       0, 1, 1, 3, 1, 1, 0, 2], dtype=int32)

In [36]:
toronto_merged = g_df
toronto_merged

Postal Code           Borough  \
0           M3A        North York   
1           M4A        North York   
2           M5A  Downtown Toronto   
3           M6A        North York   
4           M7A  Downtown Toronto   
..          ...               ...   
98          M8X         Etobicoke   
99          M4Y  Downtown Toronto   
100         M7Y      East Toronto   
101         M8Y         Etobicoke   
102         M8Z         Etobicoke   

                                         Neighbourhood   Latitude  Longitude  
0                                            Parkwoods  43.753259 -79.329656  
1                                     Victoria Village  43.725882 -79.315572  
2                            Regent Park, Harbourfront  43.654260 -79.360636  
3                     Lawrence Manor, Lawrence Heights  43.718518 -79.464763  
4          Queen's Park, Ontario Provincial Government  43.662301 -79.389494  
..                                                 ...        ...        ...  
98       The Kingsway, Montgomery Road, Old Mill North  43.653654 -79.506944  
99                                Church and Wellesley  43.665860 -79.383160  
100  Business reply mail Processing Centre, South C...  43.662744 -79.321558  
101  Old Mill South, King's Mill Park, Sunnylea, Hu...  43.636258 -79.498509  
102  Mimico NW, The Queensway West, South of Bloor,...  43.628841 -79.520999  

[103 rows x 5 columns]

In [37]:
toronto_merged = g_df

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged_it3 = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighbourhood'), on='Neighbourhood')

toronto_merged_it3.head() # check the last columns!

Postal Code           Borough                                Neighbourhood  \
0         M3A        North York                                    Parkwoods   
1         M4A        North York                             Victoria Village   
2         M5A  Downtown Toronto                    Regent Park, Harbourfront   
3         M6A        North York             Lawrence Manor, Lawrence Heights   
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government   

    Latitude  Longitude 1st Most Common Venue 2nd Most Common Venue  \
0  43.753259 -79.329656                  Park     Food & Drink Shop   
1  43.725882 -79.315572           Pizza Place          Hockey Arena   
2  43.654260 -79.360636           Coffee Shop                  Park   
3  43.718518 -79.464763        Clothing Store     Accessories Store   
4  43.662301 -79.389494           Coffee Shop           Yoga Studio   

  3rd Most Common Venue 4th Most Common Venue   5th Most Common Venue  \
0           Yoga Studio   Dumpling Restaurant     Distribution Center   
1     French Restaurant           Coffee Shop   Portuguese Restaurant   
2                Bakery                   Pub          Breakfast Spot   
3              Boutique             Gift Shop  Furniture / Home Store   
4                  Bank              Beer Bar           Smoothie Shop   

  6th Most Common Venue       7th Most Common Venue 8th Most Common Venue  \
0              Dive Bar                     Dog Run      Doner Restaurant   
1          Intersection  Construction & Landscaping                 Diner   
2                  Café                     Theater                   Spa   
3           Event Space                 Coffee Shop         Women's Store   
4        Sandwich Place                        Café            Restaurant   

   9th Most Common Venue 10th Most Common Venue  
0             Donut Shop              Drugstore  
1   Ethiopian Restaurant            Escape Room  
2                Brewery             Shoe Store  
3  Vietnamese Restaurant        Airport Service  
4     Chinese Restaurant  Portuguese Restaurant

In [38]:
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighbourhood'],kmeans.labels_):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

**Iteration 4**

In [39]:
# set number of clusters by K Means
kclusters = 9

toronto_grouped_clustering = toronto_grouped.drop('Neighbourhood', 1)
# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=1).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
print(kmeans.labels_[0:10])
print(len(kmeans.labels_))

[1 5 5 5 5 5 5 5 1 5]
96


In [40]:
kmeans.labels_

array([1, 5, 5, 5, 5, 5, 5, 5, 1, 5, 0, 5, 1, 5, 5, 5, 5, 5, 5, 5, 1, 5,
       5, 1, 1, 1, 0, 5, 5, 5, 1, 5, 1, 1, 1, 5, 5, 1, 5, 4, 1, 5, 5, 5,
       1, 5, 1, 5, 5, 8, 1, 1, 1, 5, 1, 5, 6, 5, 4, 5, 5, 0, 5, 5, 5, 0,
       1, 7, 5, 1, 1, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 1, 5, 5, 5, 5, 3, 5,
       0, 1, 5, 5, 5, 1, 0, 2], dtype=int32)

In [41]:
toronto_merged = g_df
toronto_merged

Postal Code           Borough  \
0           M3A        North York   
1           M4A        North York   
2           M5A  Downtown Toronto   
3           M6A        North York   
4           M7A  Downtown Toronto   
..          ...               ...   
98          M8X         Etobicoke   
99          M4Y  Downtown Toronto   
100         M7Y      East Toronto   
101         M8Y         Etobicoke   
102         M8Z         Etobicoke   

                                         Neighbourhood   Latitude  Longitude  
0                                            Parkwoods  43.753259 -79.329656  
1                                     Victoria Village  43.725882 -79.315572  
2                            Regent Park, Harbourfront  43.654260 -79.360636  
3                     Lawrence Manor, Lawrence Heights  43.718518 -79.464763  
4          Queen's Park, Ontario Provincial Government  43.662301 -79.389494  
..                                                 ...        ...        ...  
98       The Kingsway, Montgomery Road, Old Mill North  43.653654 -79.506944  
99                                Church and Wellesley  43.665860 -79.383160  
100  Business reply mail Processing Centre, South C...  43.662744 -79.321558  
101  Old Mill South, King's Mill Park, Sunnylea, Hu...  43.636258 -79.498509  
102  Mimico NW, The Queensway West, South of Bloor,...  43.628841 -79.520999  

[103 rows x 5 columns]

In [42]:
toronto_merged = g_df

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged_it4 = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighbourhood'), on='Neighbourhood')

toronto_merged_it4.head()

Postal Code           Borough                                Neighbourhood  \
0         M3A        North York                                    Parkwoods   
1         M4A        North York                             Victoria Village   
2         M5A  Downtown Toronto                    Regent Park, Harbourfront   
3         M6A        North York             Lawrence Manor, Lawrence Heights   
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government   

    Latitude  Longitude 1st Most Common Venue 2nd Most Common Venue  \
0  43.753259 -79.329656                  Park     Food & Drink Shop   
1  43.725882 -79.315572           Pizza Place          Hockey Arena   
2  43.654260 -79.360636           Coffee Shop                  Park   
3  43.718518 -79.464763        Clothing Store     Accessories Store   
4  43.662301 -79.389494           Coffee Shop           Yoga Studio   

  3rd Most Common Venue 4th Most Common Venue   5th Most Common Venue  \
0           Yoga Studio   Dumpling Restaurant     Distribution Center   
1     French Restaurant           Coffee Shop   Portuguese Restaurant   
2                Bakery                   Pub          Breakfast Spot   
3              Boutique             Gift Shop  Furniture / Home Store   
4                  Bank              Beer Bar           Smoothie Shop   

  6th Most Common Venue       7th Most Common Venue 8th Most Common Venue  \
0              Dive Bar                     Dog Run      Doner Restaurant   
1          Intersection  Construction & Landscaping                 Diner   
2                  Café                     Theater                   Spa   
3           Event Space                 Coffee Shop         Women's Store   
4        Sandwich Place                        Café            Restaurant   

   9th Most Common Venue 10th Most Common Venue  
0             Donut Shop              Drugstore  
1   Ethiopian Restaurant            Escape Room  
2                Brewery             Shoe Store  
3  Vietnamese Restaurant        Airport Service  
4     Chinese Restaurant  Portuguese Restaurant

In [43]:
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighbourhood'],kmeans.labels_):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

**Iteration 5**

In [44]:
# set number of clusters by K Means
kclusters = 8

toronto_grouped_clustering = toronto_grouped.drop('Neighbourhood', 1)
# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=1).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
print(kmeans.labels_[0:10])
print(len(kmeans.labels_))

[1 6 1 1 6 1 1 1 6 1]
96


In [45]:
kmeans.labels_

array([1, 6, 1, 1, 6, 1, 1, 1, 6, 1, 2, 1, 1, 1, 1, 1, 6, 6, 1, 6, 0, 6,
       1, 6, 1, 1, 2, 6, 1, 1, 1, 1, 6, 1, 1, 1, 1, 6, 6, 4, 6, 6, 1, 1,
       6, 1, 2, 1, 1, 7, 2, 1, 6, 1, 2, 1, 1, 1, 4, 1, 6, 2, 1, 1, 1, 2,
       6, 4, 1, 1, 1, 6, 1, 1, 6, 1, 1, 1, 6, 6, 1, 6, 6, 1, 1, 6, 5, 6,
       2, 6, 1, 6, 1, 1, 2, 3], dtype=int32)

In [46]:
toronto_merged = g_df
toronto_merged

Postal Code           Borough  \
0           M3A        North York   
1           M4A        North York   
2           M5A  Downtown Toronto   
3           M6A        North York   
4           M7A  Downtown Toronto   
..          ...               ...   
98          M8X         Etobicoke   
99          M4Y  Downtown Toronto   
100         M7Y      East Toronto   
101         M8Y         Etobicoke   
102         M8Z         Etobicoke   

                                         Neighbourhood   Latitude  Longitude  
0                                            Parkwoods  43.753259 -79.329656  
1                                     Victoria Village  43.725882 -79.315572  
2                            Regent Park, Harbourfront  43.654260 -79.360636  
3                     Lawrence Manor, Lawrence Heights  43.718518 -79.464763  
4          Queen's Park, Ontario Provincial Government  43.662301 -79.389494  
..                                                 ...        ...        ...  
98       The Kingsway, Montgomery Road, Old Mill North  43.653654 -79.506944  
99                                Church and Wellesley  43.665860 -79.383160  
100  Business reply mail Processing Centre, South C...  43.662744 -79.321558  
101  Old Mill South, King's Mill Park, Sunnylea, Hu...  43.636258 -79.498509  
102  Mimico NW, The Queensway West, South of Bloor,...  43.628841 -79.520999  

[103 rows x 5 columns]

In [47]:
toronto_merged = g_df

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged_it5 = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighbourhood'), on='Neighbourhood')

toronto_merged_it5.head()

Postal Code           Borough                                Neighbourhood  \
0         M3A        North York                                    Parkwoods   
1         M4A        North York                             Victoria Village   
2         M5A  Downtown Toronto                    Regent Park, Harbourfront   
3         M6A        North York             Lawrence Manor, Lawrence Heights   
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government   

    Latitude  Longitude 1st Most Common Venue 2nd Most Common Venue  \
0  43.753259 -79.329656                  Park     Food & Drink Shop   
1  43.725882 -79.315572           Pizza Place          Hockey Arena   
2  43.654260 -79.360636           Coffee Shop                  Park   
3  43.718518 -79.464763        Clothing Store     Accessories Store   
4  43.662301 -79.389494           Coffee Shop           Yoga Studio   

  3rd Most Common Venue 4th Most Common Venue   5th Most Common Venue  \
0           Yoga Studio   Dumpling Restaurant     Distribution Center   
1     French Restaurant           Coffee Shop   Portuguese Restaurant   
2                Bakery                   Pub          Breakfast Spot   
3              Boutique             Gift Shop  Furniture / Home Store   
4                  Bank              Beer Bar           Smoothie Shop   

  6th Most Common Venue       7th Most Common Venue 8th Most Common Venue  \
0              Dive Bar                     Dog Run      Doner Restaurant   
1          Intersection  Construction & Landscaping                 Diner   
2                  Café                     Theater                   Spa   
3           Event Space                 Coffee Shop         Women's Store   
4        Sandwich Place                        Café            Restaurant   

   9th Most Common Venue 10th Most Common Venue  
0             Donut Shop              Drugstore  
1   Ethiopian Restaurant            Escape Room  
2                Brewery             Shoe Store  
3  Vietnamese Restaurant        Airport Service  
4     Chinese Restaurant  Portuguese Restaurant

In [48]:
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighbourhood'],kmeans.labels_):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

Iteration 5 is the version that appears to have the most even split in clusters, so we can say that 8 is the ideal number of clusters, when viewing similarity of neighbourhoods in toronto, when based on most common venues